apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline

spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main
    - name: build-image

  tasks:

    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      params:
        - name: image
          value: python:3.9-slim

        # IMPORTANT: flake8 expects ARRAY, not string
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"

        - name: path
          value: "."
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - clone
      params:
        - name: args
          value: "-v --with-spec --spec-color"
        - name: database_uri
          value: "sqlite:///test.db"
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - lint
        - nose
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
      params:
        - name: SCRIPT
          value: |
            echo "Updating manifest..."
            sed -i "s|us.icr.io/sn-labs-sakshyasinha/accounts:1|$(params.build-image)|g" deploy/deployment.yaml
            cat deploy/deployment.yaml
            echo "Deploying to OpenShift..."
            oc apply -f deploy/
            oc get pods -l app=accounts